name: CMake Build and Google Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Windows or Mac if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Build Directory
      uses: actions/cache@v3
      with:
        # Cache the "build" directory
        path: build
        # Invalidate the cache if CMakeLists.txt changes.
        key: ${{ runner.os }}-build-${{ hashFiles('CMakeLists.txt') }}

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y cmake g++ make

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build

    - name: Run Google Tests
      run: ctest --test-dir build --output-on-failure
